export function createArt({img,link,button,arrow}) {
  const motion = (className='') => `<figure class="motion-study ${className}"><div class="motion-screen"><video muted loop playsinline preload="none" poster="/assets/studio-bts.jpg" data-motion-src="/assets/studio-bts.mp4" aria-hidden="true"></video><button class="motion-toggle" data-motion-toggle aria-label="Bewegtbild abspielen" hidden>Bewegtbild abspielen</button></div><figcaption>Behind the scenes bei FPMC</figcaption></figure>`;
  return {
    motion,
    header(active,path) {
      return `<a class="skip" href="#main">Zum Inhalt</a><header class="header"><div class="header-inner wrap"><a class="brand" href="/" aria-label="FPMC – Startseite"><span class="wordmark">FPMC</span></a><a class="header-quick" href="${path==='/kontakt/'?'#anfrage':'/kontakt/'}" aria-label="Projekt anfragen">Anfragen ${arrow}</a><button class="menu-toggle" data-menu-toggle aria-expanded="false" aria-controls="main-nav" aria-label="Menü öffnen">Menü +</button><nav class="desktop-nav" data-nav id="main-nav" aria-label="Hauptnavigation">${[['Projekte','/projekte/'],['Leistungen','/leistungen/'],['Studio','/studio/'],['Label','/label/']].map(([n,u])=>`<a href="${u}" ${active===n?`aria-current="${path===u?'page':'location'}"`:''}>${n}</a>`).join('')}${button('Projekt anfragen',path==='/kontakt/'?'#anfrage':'/kontakt/')}</nav></div></header>`;
    },
    footer(path,type,contact) {
      return `${path==='/kontakt/'?'':`<section class="cta-section"><div class="wrap cta-layout"><div class="cta-copy"><h2>${path==='/label/'?'Dein nächster<br>Release.':'Dein nächstes<br>Projekt.'}</h2></div><div class="cta-invitation"><p>${path==='/label/'?'Musikproduktion, Musikvideo oder ein gemeinsamer Release. Erzähl uns, woran du arbeitest.':'Eine Idee, ein Track oder eine Referenz. Erzähl uns, was entstehen soll.'}</p><div class="actions">${button(type?`${type} anfragen`:'Projekt anfragen',contact)}<a class="quiet-link" href="mailto:hello@fpmc.house">hello@fpmc.house</a></div></div></div></section>`}<footer class="footer"><div class="wrap"><div class="footer-top"><div class="footer-brand"><p>Film Production<br>Music Club</p></div><div><p>Frankenforster Straße 2<br>51427 Bergisch Gladbach</p><div class="footer-links"><a href="mailto:hello@fpmc.house">hello@fpmc.house</a><a href="tel:+4915567485270">+49 1556 7485270</a></div></div><nav class="footer-links" aria-label="Weitere Seiten"><a href="/projekte/">Projekte</a><a href="/leistungen/">Leistungen</a><a href="/studio/">Studio</a><a href="/label/">Label</a><a href="/kontakt/">Kontakt</a></nav><div class="footer-links"><a href="https://www.instagram.com/fpmc.house" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://www.youtube.com/@fpmc-house" target="_blank" rel="noopener noreferrer">YouTube ↗</a><a href="https://www.tiktok.com/@fpmc.house" target="_blank" rel="noopener noreferrer">TikTok ↗</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} FPMC GbR</span><div><a href="/impressum/">Impressum</a><a href="/datenschutz/">Datenschutz</a><a href="/links/">Links</a></div></div><a class="footer-stamp" href="/" aria-label="FPMC – Startseite"><span>F</span><span>P</span><span>M</span><span>C</span></a></div></footer>`;
    },
    pageHero(eyebrow,title,description,actions='',breadcrumbs='') {
      const lines=title.split('<br>');
      const headline=lines.map((line,i)=>`<span class="title-line" style="--line-index:${i}">${i===lines.length-1&&lines.length>1?`<span class="title-emphasis">${line}</span>`:line}</span>`).join('');
      return `<section class="page-hero"><div class="wrap">${breadcrumbs?`<nav class="breadcrumbs" aria-label="Brotkrumennavigation"><a href="/">Start</a><span aria-hidden="true">/</span>${breadcrumbs}</nav>`:''}<div class="page-heading"><h1>${headline}</h1></div><div class="page-intro"><p>${description}</p>${actions?`<div class="actions">${actions}</div>`:''}</div></div></section>`;
    },
    serviceHero(s) {
      const title=s.h1.split('<br>').map((line,i)=>`<span class="title-line" style="--line-index:${i}">${line}</span>`).join('');
      return `<section class="service-hero"><div class="wrap"><nav class="breadcrumbs" aria-label="Brotkrumennavigation"><a href="/">Start</a><span aria-hidden="true">/</span><a href="/leistungen/">Leistungen</a><span aria-hidden="true">/</span><span>${s.name}</span></nav><div class="service-hero-layout"><div class="service-hero-copy"><h1>${title}</h1><p>${s.desc}</p><div class="actions">${button(s.type==='Audio & Musik'?'Audioprojekt anfragen':s.type+' anfragen','/kontakt/?projekt='+encodeURIComponent(s.type))}</div></div><div class="service-hero-media">${img(s.image,s.alt,'',true)}</div></div></div></section>`;
    },
    labelHero() {
      return `<section class="label-masthead"><div class="wrap"><div class="label-opening"><h1>FPMC <span>Label.</span></h1><p>Eigene Veröffentlichungen.<br>Musik und Film aus einem Haus.</p></div><div class="release-layout" id="release"><div class="release-artwork">${img('radi.jpg','Redstar Radi vor einem Sportwagen bei Nacht','',true)}</div><div class="release-copy"><h2>Redstar<br>Radi.</h2><p class="arabic-title" lang="ar" dir="rtl">موسم الهجرة الي الشمال</p><p class="release-name">Mawsim Al Hijra Ila Al Shamal</p><p>Der erste Release von FPMC Label.<br>Veröffentlicht am 7. August 2026.</p><div class="actions">${button('Musikvideo ansehen','#video')}${link('Auf Spotify anhören','https://open.spotify.com/track/4u0QqfrgJZInscjI6hBbpZ')}</div>${link('Die Produktion entdecken','/projekte/redstar-radi/')}</div></div></div></section>`;
    },
    studioHero() {
      return `<section class="studio-masthead"><div class="wrap studio-opening"><div class="studio-opening-copy"><h1>Vier Leute.<br>Ein Haus.</h1><p>Film und Regie, Sound, Design und Organisation. Ein unabhängiges Team aus Bergisch Gladbach.</p><p>Unser Team verbindet den deutschsprachigen Raum und die arabische Welt.</p>${link('Über dein Projekt sprechen','/kontakt/')}</div>${motion('studio-opening-film')}</div></section>`;
    },
    contact(form) {
      return `<section class="contact-workspace"><div class="wrap contact-sheet"><div class="contact-editorial"><h1>Was hast<br>du vor?</h1><p class="contact-intro">Ein Track, ein Film oder eine erste Idee. Erzähl uns, woran du arbeitest.</p><div class="contact-direct"><div class="contact-address"><a href="mailto:hello@fpmc.house">hello@fpmc.house</a><a href="tel:+4915567485270">+49 1556 7485270</a><a href="https://wa.me/4915567485270" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a></div></div></div><div class="contact-letter" id="anfrage"><h2>Woran denkst du?</h2><p class="contact-how">Wir erstellen deinen E-Mail-Entwurf. Du prüfst ihn und sendest ihn in deinem Mailprogramm ab.</p>${form}</div></div></section>`;
    },
    home() {
      const serviceItems=[
        ['01','Film.','Werbefilm, dokumentarische Begleitung und Postproduktion.','filmproduktion'],
        ['02','Musikvideo.','Konzept, Dreh und Schnitt für deinen Track.','musikvideoproduktion'],
        ['03','Audio.','Musikproduktion, Sounddesign und Podcasts.','audioproduktion']
      ];
      return `<section class="home-stage"><div class="stage-image">${img('release-still.jpg','Filmframe aus dem Musikvideo von Redstar Radi','',true)}</div><div class="wrap stage-content"><h1>Film.<br>Musik.</h1><div class="stage-introduction"><p class="stage-statement">Aus einem Haus.</p><p>Filmproduktion, Musikvideos und Sound. Für Artists, Labels und Marken.</p><div class="actions">${button('Projekt anfragen','/kontakt/')}${link('Arbeiten ansehen','/projekte/')}</div></div></div><div class="wrap stage-film"><a href="/projekte/redstar-radi/#musikvideo"><span>Redstar Radi</span><span>Musikvideo ansehen ${arrow}</span></a></div></section>
      <section class="home-services section"><div class="wrap"><div class="section-head"><div><h2>Unsere<br>Produktion.</h2></div><p>Komplette Produktionen oder einzelne Leistungen: Konzept, Dreh, Schnitt und Sound.</p></div><div class="service-overview">${serviceItems.map(([n,title,description,slug])=>`<a class="service-overview-item" href="/leistungen/${slug}/"><h3>${title}</h3><p>${description}</p><span class="service-more" aria-hidden="true">${arrow}</span></a>`).join('')}</div><div class="digital-note"><p>Auch im Digitalen: Websites und Werbeclips für Unternehmen.</p>${link('Web & Digital','/leistungen/web-digital/')}</div></div></section>
      <section class="home-studio section"><div class="wrap home-studio-layout">${motion('home-studio-motion')}<div class="home-studio-copy"><h2>Vier Köpfe.<br>Ein Team.</h2><p>Regie, Musikproduktion, Design und Organisation. Vier Perspektiven auf dein Projekt – mit kurzen Wegen zwischen Bild und Ton.</p><div class="studio-credits"><span>Saeed Marwush <small>Film & Regie</small></span><span>Jasper Beckmann <small>Sound & Musik</small></span><span>Dilara Yurdadönen <small>Organisation</small></span><span>Hazem Hokan <small>Design & Musik</small></span></div>${link('Team & Arbeitsweise','/studio/')}</div></div></section>
      <section class="label-feature section"><div class="wrap label-feature-layout"><div><h2>FPMC Label.<br>Redstar Radi.</h2><p>Unser erster Release mit Redstar Radi. Musikproduktion und Film aus dem eigenen Haus.</p>${link('Redstar Radi & das Label','/label/')}</div><a class="label-feature-image" href="/label/" aria-label="Redstar Radi und FPMC Label entdecken">${img('radi.jpg','Künstlerportrait von Redstar Radi')}</a></div></section>`;
    }
  };
}
